package com.stratuslite.audit;

public enum ControlPlaneEventType {
    WORKLOAD_CREATED,
    PLACEMENT_CREATED,
    LOAD_SPIKE_SIMULATED,
    CELL_FAILURE_SIMULATED,
    RECONCILER_SWEEP,
    REBALANCE_EXECUTED,
    REBALANCE_ROLLED_BACK
}
